version: '3'

services:

  db:
    container_name: db
    image: mariadb:10.11
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - dbdata.env  
    ports:
      - "3306:3306"
    networks:
      - dbdata

  trust:
    image: indigoiam/egi-trustanchors
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - cabundle:/etc/pki

  ngix:
    image: nginx
    dns_search: cern.ch
    container_name: iam

    environment:
      TZ: Europe/Rome
      NGINX_HOST: iam
      NGINX_PORT: 443
    ports:
      - "443:443"
    volumes:
      - /dev/urandom:/dev/random
      - ./assets/iam.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/grid-security/:/etc/grid-security/

  iam:
    image: indigoiam/iam-login-service:v1.8.2
    volumes:
      - "./assets/keystore.jwks:/keystore.jwks:ro"
      - trustanchors:/etc/grid-security/certificates
    env_file:
      - iam.env
    ports:
      - "8080:8080"
    networks:
      - dbdata

volumes:
  dbdata:
  trustanchors:
  cabundle:

networks:
  dbdata: